### ISSUE TITLE
ValueError: setting an array element with a sequence. 

### ISSUE THREAD

**Issue by yhx-tj** [Zhihan1996/DNABERT_2#21]
Hello, I was testing the finetune code but I got this error:

>  Traceback (most recent call last):██████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 51.26it/s]
  File "bin/DNABERT_2/finetune/train.py", line 286, in <module>
    train()
  File "bin/DNABERT_2/finetune/train.py", line 268, in train
    trainer.train()
  File "/miniconda/envs/dna/lib/python3.8/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/miniconda/envs/dna/lib/python3.8/site-packages/transformers/trainer.py", line 2020, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/miniconda/envs/dna/lib/python3.8/site-packages/transformers/trainer.py", line 2321, in _maybe_log_save_evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
  File "/miniconda/envs/dna/lib/python3.8/site-packages/transformers/trainer.py", line 3053, in evaluate
    output = eval_loop(
  File "/miniconda/envs/dna/lib/python3.8/site-packages/transformers/trainer.py", line 3353, in evaluation_loop
    metrics = self.compute_metrics(EvalPrediction(predictions=all_preds, label_ids=all_labels))
  File "bin/DNABERT_2/finetune/train.py", line 204, in compute_metrics
    return calculate_metric_with_sklearn(logits, labels)
  File "bin/DNABERT_2/finetune/train.py", line 190, in calculate_metric_with_sklearn
    predictions = np.argmax(logits, axis=-1)
  File "<__array_function__ internals>", line 200, in argmax
  File "/miniconda/envs/dna/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 1242, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out, **kwds)
  File "/miniconda/envs/dna/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/miniconda/envs/dna/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 471) + inhomogeneous part.

**Comment by Sudhendra** [comment]
I fixed the issue. If and when the author decides to merge my pull request, you wont face this issue anymore. @Zhihan1996

**Comment by yhx-tj** [comment]
Thanks a lot!
