### ISSUE TITLE
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. 

### ISSUE THREAD

**Issue by leannmlindsey** [Zhihan1996/DNABERT_2#25]
I am trying to run the finetuning example that you have on the github and I keep getting this error.  I am able to successfully run the quickstart section of your github.

```Error:
The provided data_path is /uufs/chpc.utah.edu/common/home/u1323098/sundar-group-space2/PHAGE/MODELS/GUE/prom/prom_300_tata
WARNING:root:Perform single sequence classification...
WARNING:root:Perform single sequence classification...
WARNING:root:Perform single sequence classification...
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
/uufs/chpc.utah.edu/common/home/u1323098/.cache/huggingface/modules/transformers_modules/zhihan1996/DNABERT-2-117M/5fd206e1a13cee3ef4a608677312175eb6f8143d/bert_layers.py:125: UserWarning: Unable to import Triton; defaulting MosaicBERT attention implementation to pytorch (this will reduce throughput when using this model).
  warnings.warn(
Some weights of the model checkpoint at zhihan1996/DNABERT-2-117M were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.bias', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at zhihan1996/DNABERT-2-117M and are newly initialized: ['classifier.bias', 'classifier.weight', 'bert.pooler.dense.bias', 'bert.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using cuda_amp half precision backend
***** Running training *****
  Num examples = 4,904
  Num Epochs = 3
  Instantaneous batch size per device = 32
  Total train batch size (w. parallel, distributed & accumulation) = 32
  Gradient Accumulation steps = 1
  Total optimization steps = 462
  Number of trainable parameters = 117,070,082
 43%|████████████████████████████████████████████████████████████▎                                                                               | 199/462 [00:12<00:12, 21.47it/s]***** Running Evaluation *****
  Num examples = 613
  Batch size = 32
                                                                                                                                                                                  Traceback (most recent call last):███████████████████████████████████████████████████████████████████████████████████████████████████▊              | 18/20 [00:00<00:00, 80.37it/s]
  File "train.py", line 286, in <module>
    train()
  File "train.py", line 268, in train
    trainer.train()
  File "/uufs/chpc.utah.edu/common/home/u1323098/software/pkg/miniconda3/envs/dna/lib/python3.8/site-packages/transformers/trainer.py", line 1662, in train
    return inner_training_loop(
  File "/uufs/chpc.utah.edu/common/home/u1323098/software/pkg/miniconda3/envs/dna/lib/python3.8/site-packages/transformers/trainer.py", line 2006, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/uufs/chpc.utah.edu/common/home/u1323098/software/pkg/miniconda3/envs/dna/lib/python3.8/site-packages/transformers/trainer.py", line 2287, in _maybe_log_save_evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
  File "/uufs/chpc.utah.edu/common/home/u1323098/software/pkg/miniconda3/envs/dna/lib/python3.8/site-packages/transformers/trainer.py", line 2993, in evaluate
    output = eval_loop(
  File "/uufs/chpc.utah.edu/common/home/u1323098/software/pkg/miniconda3/envs/dna/lib/python3.8/site-packages/transformers/trainer.py", line 3281, in evaluation_loop
    metrics = self.compute_metrics(EvalPrediction(predictions=all_preds, label_ids=all_labels))
  File "train.py", line 204, in compute_metrics
    return calculate_metric_with_sklearn(logits, labels)
  File "train.py", line 190, in calculate_metric_with_sklearn
    predictions = np.argmax(logits, axis=-1)
  File "<__array_function__ internals>", line 200, in argmax
  File "/uufs/chpc.utah.edu/common/home/u1323098/software/pkg/miniconda3/envs/dna/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 1242, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out, **kwds)
  File "/uufs/chpc.utah.edu/common/home/u1323098/software/pkg/miniconda3/envs/dna/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/uufs/chpc.utah.edu/common/home/u1323098/software/pkg/miniconda3/envs/dna/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 613) + inhomogeneous part.
 43%|████████████████████████████████████████████████████████████▌                                                                               | 200/462 [00:12<00:16, 15.91it/s]
 ```
                                                                                                                                                 
Here are the installation instructions that are working on my computer system (university of utah CHPC)
```
salloc --account=soc-gpu-np --partition=soc-gpu-np --nodes=1 --gres=gpu:a100:1

conda activate dna
cd sundar-group-space2/PHAGE/MODELS/DNABERT_2/
python3 -m pip install -r requirements.txt
pip uninstall triton
```
 previously I had changed the requirements.txt to read
 ```
einops  
transformers==4.28.0  
peft  
omegaconf  
torch  
evaluate  
accelerate
```
I also had to change the learning rate from ${lr} to 1e-4 in run_dnabert2.sh

**Comment by leannmlindsey** [comment]
I was able to get past this error by following the instructions from @raphaelmourad on Issue #19

**Comment by Zhihan1996** [comment]
Thank you for the updates, and thank @raphaelmourad for providing solutions.
